name: Docker Image CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  docker:
    name: Publish - Docker Hub
    runs-on: ${{ inputs.runnerName }}
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
    steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
           java-version: 11.0.4
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker image
          run: docker push $REPO
        - name: Image Scan
          uses: aquasecurity/trivy-action@master
          with:
           image-ref: ${{ env.REPO }}
           security-checks: 'vuln,secret,config'
           format: 'sarif'
           output: 'trivy-image-results.sarif'
           severity: 'CRITICAL,HIGH'
        - name: Display Scan Results
          run: cat trivy-image-results.sarif

