name: Setup Environment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt update
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        docker --version

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh
        gh --version

    - name: Set up GitHub Token for gh
      run: |
        echo "${GH_TOKEN}" | gh auth login --with-token -

    - name: Install GitHub Actions Importer CLI extension
      run: gh extension install github/gh-actions-importer

    - name: Verify Actions Importer extension installation
      run: gh actions-importer -h

    - name: GitHub Authentication and Additional Commands
      run: |
        # Additional commands after authentication
        echo "Running additional commands..."
        gh repo view
        gh issue list

        # You can add more commands here
