
name: "java_app_pipeline"

on:
  push:
   branches: [ feature ]
   # branches: [ main, develop, "feature/*", "hotfix/*", "release/*" ]

jobs:
  
  Codebuild:
    name: Codebuild
    uses: "./.github/workflows/Build_Stage.yml"
    with:
       runnerName: "github-testnew-runner"
       java-version: "11"
       distribution: "temurin"
       cache: "maven" 
  docker:
      name: Publish - Docker Hub
      runs-on: ubuntu-latest
      needs: [ Codebuild ]
      env:
       REPO: ${{ secrets.DOCKER_REPO }}

      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
           java-version: 11.0.4
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: docker build -t ${{ env.REPO }}:latest -t ${{ env.REPO }}:${{ github.sha }} .

        - name: Publish Docker image
          run: docker push $REPO
