name: Trivy Scan

on:
  push:
    branches:
      - develop

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy
        run: |
          # Install Trivy (if not already installed)
          curl -sfL https://install.trivy.io | sh -s -- -b /usr/local/bin

          # Scan container image new image add new image
          trivy image <your-image-name>
